apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john.doe1
spec:
  profile:
    displayName: John Doe1
    email: john.doe1@tui.com
  memberOf: [foobar]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john.doe2
spec:
  profile:
    displayName: John Doe2
    email: john.doe2@tui.com
  memberOf: [foobar]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john.doe3
spec:
  profile:
    displayName: John Doe3
    email: john.doe3@tui.com
  memberOf: [foobar]
---
