apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding-glamour
  title: Glamour Onboarding
  description: Template to create a glamour-config repo in your root Gitlab group.
  tags:
    - infrastructure
    - glamour
    - recommended
  links:
    - url: https://source.tui/cloud/cloud-fabric/glamour/-/tree/dev/docs
      title: Glamour user guide
      icon: docs
spec:
  owner: enablers-cloudfabric
  type: service

  parameters:
    - title: Basic configuration
      required:
        - repository_location
        - owner
      properties:
        repository_location:
          title: Location of your root group in OneSource with no leading or trailing slash
          type: string
          description: Enter the path of your Gitlab root group to create this repo in there.
          ui:field: NoLeadingOrTrailingSlashValuePicker
        owner:
          title: Owner
          type: string
          description: Name of your team group in Runway
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

  steps:
    - id: fetch
      name: Template Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          repository_location: ${{ parameters.repository_location }}
          projectId: ${{ steps.getgitlabprojectid.output.projectId }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: source.tui?owner=${{ parameters.repository_location }}&repo=glamour-config
        defaultBranch: main
        repoVisibility: internal

    - id: getgitlabprojectid
      name: Get GitLab Project ID
      action: tui:get-gitlab-projectid
      input:
        remoteUrl: ${{ steps.publish.output.remoteUrl }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Create token for Glamour
        url: https://source.tui/groups/${{ parameters.repository_location }}/-/settings/access_tokens
        icon: user
      - title: Add token as masked variable GLAMOUR_TOKEN
        url: ${{ steps.publish.output.remoteUrl }}/-/settings/ci_cd
        icon: user
      - title: Enable shared Gitlab runner
        url: ${{ steps.publish.output.remoteUrl }}/-/settings/ci_cd
        icon: user
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
