apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding-glamour
  title: Glamour Onboarding
  description: Template to create a glamour-config repo in your root Gitlab group.
    
spec:
  owner: backstage
  type: service

  parameters:
    - title: Basic configuration
      properties:
        repository_location:
          title: Location of your root group in OneSource with no leading or trailing slash
          type: string
          description: Enter the path of your Gitlab root group to create this repo in there.
        owner:
          title: Owner
          type: string
          description: Name of your team group in Runway
